### ISSUE TITLE
Tardis forgets last known position on server closing and rejoin, if in the Tardis closing the server (Forge)

### ISSUE THREAD

**Issue by Bonkjumper** [Suff99/TardisRefined#160]
### Issue description

So, I was making a trip back home in my Tardis, when I felt it was a good time to turn off for the day, so I leave, skip a few days later I come back to my world, I spawn in my tardis with no issue, but I notice I couldn't leave my tardis, thinking it's perhaps I didn't land in a dimension that hasn't loaded yet I check the computer bank to see where I am, however I couldn't use it, all the other controls worked but the computer bank, so I decide I'll just demat back to where I normally land my tardis, I try to demat and the server crashes, The immediate crash log tells me the exact problem, but there's probably more to it, which is why I am reporting it here. My world is probably bricked and I am kinda an idiot for not backing it up, but eh, this gives me a chance to do a good restructure of my self modpack.

### Steps to reproduce

1. Enter a Tardis
2. Remain in a Tardis
3.Close the server/world while maintaining step 2
4. renter the server
5. attempt any form of dematerialization
6. Server dies and any form of escaping the Tardis fails

### Minecraft version

1.19.4 (Latest)

### Mod Loader Platform type

Forge

### Mod Loader version

Forge Version 43.2.14

### Tardis Refined version

v1.0

### Attach the relevant crash report file or log file: (Don't know how to find a crash report file? See the [Minecraft Wiki Tutorial](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report)

https://pastebin.com/t1CA8Ny2

**Comment by Bonkjumper** [comment]
The mod list is in the crash-log if you need it, but if you need any more details, I am more then happy to share

**Comment by AlienXtream** [comment]
thats not the whole crash report (actually missing the crash itself). if its what i assume i do believe this is a known issue. though your world shouldn't be bricked. this happens with modded dimensions. not sure on the details but the crash is mroe of a failsafe when the dimension is "null". the tardis position will be reset to 0, 0, 0 in the overworld next time you join back. again, thats assuming its the dimension bug. something something blame forge/vanilla dimensions stuff. not an expert on this stuff.

**Comment by Bonkjumper** [comment]
Oh shoot, did I forget to copy that in?, ok I’ll later update it

**Comment by AlienXtream** [comment]
i assume its basically the same as the crash report in this one https://github.com/CommandrMoose/TardisRefined/issues/154

**Comment by Bonkjumper** [comment]
It was similar, but it was already landed, so perhaps it is the same issue, but can be triggered by other circumstances

**Comment by Bonkjumper** [comment]
There the Log was updated

**Comment by tEMMIE6823** [comment]
Just incase if it helps I have the error right here


1. [12:27:69] [Server thread/ERROR]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundInteractPacket@3733c96c, suppressing error
2. java.lang.NullPointerException: Cannot invoke "whocraft.tardis_refined.common.tardis.TardisNavLocation.getPosition()" because "currentLocation" is null
3. 	at TRANSFORMER/tardis_refined@1.0.1/whocraft.tardis_refined.common.network.messages.OpenMonitorMessage.<init>(OpenMonitorMessage.java:34)
4. 	at TRANSFORMER/tardis_refined@1.0.1/whocraft.tardis_refined.common.tardis.control.ship.MonitorControl.onRightClick(MonitorControl.java:26)
5. 	at TRANSFORMER/tardis_refined@1.0.1/whocraft.tardis_refined.common.entity.ControlEntity.lambda$handleRightClick$2(ControlEntity.java:311)
6. 	at java.base/java.util.Optional.ifPresent(Optional.java:178)
7. 	at TRANSFORMER/tardis_refined@1.0.1/whocraft.tardis_refined.common.entity.ControlEntity.handleRightClick(ControlEntity.java:296)
8. 	at TRANSFORMER/tardis_refined@1.0.1/whocraft.tardis_refined.common.entity.ControlEntity.m_7111_(ControlEntity.java:178)
9. 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.network.ServerGamePacketListenerImpl$1.lambda$onInteraction$0(ServerGamePacketListenerImpl.java:1568)
10. 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.network.ServerGamePacketListenerImpl$1.m_143678_(ServerGamePacketListenerImpl.java:1550)
11. 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.network.ServerGamePacketListenerImpl$1.m_142143_(ServerGamePacketListenerImpl.java:1565)
12. 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.protocol.game.ServerboundInteractPacket$InteractionAtLocationAction.m_142457_(ServerboundInteractPacket.java:146)
13. 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.protocol.game.ServerboundInteractPacket.m_179617_(ServerboundInteractPacket.java:66)
14. 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.network.ServerGamePacketListenerImpl.m_6946_(ServerGamePacketListenerImpl.java:1546)
15. 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.protocol.game.ServerboundInteractPacket.m_5797_(ServerboundInteractPacket.java:53)
16. 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.protocol.game.ServerboundInteractPacket.m_5797_(ServerboundInteractPacket.java:13)
17. 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22)
18. 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.TickTask.run(TickTask.java:18)
19. 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157)
20. 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
21. 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:763)
22. 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:157)
23. 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131)
24. 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:746)
25. 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:740)
26. 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116)
27. 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:725)
28. 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:658)
29. 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244)
30. 	at java.base/java.lang.Thread.run(Thread.java:833)


sadly ive lost almost 10 worlds due to this error all of them hardcore :/

**Comment by UNSPOKEN-GT** [comment]
![7l1cnb-1985475279](https://github.com/Suff99/TardisRefined/assets/104364978/64def6e1-2ae4-4acf-acc0-aec260e86bc8)

**Comment by tEMMIE6823** [comment]
> ![7l1cnb-1985475279](https://user-images.githubusercontent.com/104364978/280214308-64def6e1-2ae4-4acf-acc0-aec260e86bc8.png)

🤯

**Comment by Suff99** [comment]
Fixed
